In [206]:
import numpy as np

arr = np.array(([1, 2, 3],[4, 5, 6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [207]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [208]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [209]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [210]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [211]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [212]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [213]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
arr3[5]

5

In [215]:
arr3[5:8]

array([5, 6, 7])

In [216]:
arr3[5:8] = 12
arr3

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [217]:
arr_slice = arr3[5:8]
arr_slice

array([12, 12, 12])

In [218]:
arr_slice[1] = 12345
arr3

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [219]:
arr_slice[:] = 64
arr3

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [220]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [221]:
arr2d[0][2]

3

In [222]:
arr2d[0,2]

3

In [223]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [224]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [226]:
arr3d[0] =42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [227]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [228]:
arr3d[1,0]

array([7, 8, 9])

In [229]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [230]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [231]:
arr2d[1,:2]

array([4, 5])

In [232]:
arr2d[:2,2]

array([3, 6])

In [233]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [234]:
# 布尔索引
names = np.array(['Bob','Joe','will','Bob','will','Joe','Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'will', 'Bob', 'will', 'Joe', 'Joe'], dtype='<U4')

In [235]:
data

array([[-0.06170086,  0.40246625,  0.14233241, -0.05493207],
       [-0.76806725, -1.8050786 ,  0.94804087,  2.32013923],
       [-0.99292133,  1.60162388, -0.57591495,  1.39460475],
       [-0.24284967, -0.7537414 , -0.2534144 ,  1.4034922 ],
       [ 0.43069865,  0.40494477,  0.22043615,  0.60300276],
       [ 1.39074328, -0.95379438, -0.96160991, -0.51428207],
       [-0.32631653, -1.11000419, -0.81051984, -0.51874523]])

In [236]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [237]:
data[names == 'Bob']

array([[-0.06170086,  0.40246625,  0.14233241, -0.05493207],
       [-0.24284967, -0.7537414 , -0.2534144 ,  1.4034922 ]])

In [238]:
# 神奇索引
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [239]:
ar = np.arange(32)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [240]:
ar.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [241]:
a = np.arange(15).reshape((5,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [242]:
a.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [243]:
a1 = np.random.randn(6,3)
a1

array([[-0.21439926,  1.39764472, -0.15363264],
       [-1.43304145,  0.6327999 ,  1.21659182],
       [-1.70478012, -0.82498613, -2.32246026],
       [ 0.03696666, -0.36525157,  0.78461863],
       [-0.18769616, -0.6680492 ,  0.88554488],
       [ 0.20580572, -1.79478863,  0.46786575]])

In [244]:
np.dot(a1.T, a1)

array([[ 5.08480248, -0.05755214,  2.20787711],
       [-0.05755214,  6.83541325,  0.75324199],
       [ 2.20787711,  0.75324199,  8.51623476]])

In [247]:
a2 = np.arange(24).reshape((3,2,4))
a2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [249]:
da = a2.transpose((1,0,2))
da

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]]])

In [250]:
a2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [251]:
a3 = np.arange(16).reshape((2,2,4))
a3.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])