### 通用函数：快速的逐元素数组函数

In [1]:
import numpy as np

a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(a1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.21372183,  0.04092161,  0.20041659, -1.78164747, -0.12978112,
       -0.78803373, -0.66250049,  0.20218204])

In [5]:
y

array([-0.6502765 , -0.59815985,  0.49810597, -1.76052917, -0.23654317,
        1.26391864,  0.98336052,  0.10352643])

In [6]:
np.maximum(x,y)

array([-0.21372183,  0.04092161,  0.49810597, -1.76052917, -0.12978112,
        1.26391864,  0.98336052,  0.20218204])

In [7]:
a3 = np.random.randn(7)*5
a3

array([-1.7434267 , -1.06945247, -3.94496308, -2.42579939, -0.02444174,
        4.2121001 ,  3.98899543])